### ISSUE TITLE
The usage section could use the details/examples from the old "IUS Client Usage Guide" 

### ISSUE THREAD

**Issue by i-give-up** [iuscommunity/ius.io#10]
The [IUS Client Usage Guide](https://github.com/iuscommunity/sphinx_iuscommunity/blob/master/pages/IUSClientUsageGuide.rst) seems to contain a lot more information than the current [Usage Guide](https://github.com/iuscommunity/ius.io/blob/master/docs/Usage.md). For example, the latter is missing

```
sudo yum install yum-plugin-replace
```

I think it would be helpful to link to the github page of the old guide in the new guide during the transition period seeing that https://iuscommunity.org is going to be redirected to https://ius.io soon.

**Comment by carlwgeorge** [comment]
Howdy @i-give-up,

The new usage guide mentions the replace plugin, linking to it's [homepage](https://github.com/iuscommunity/yum-plugin-replace).  It also includes a text example of usage and a link to an [asciinema screencast demo](https://asciinema.org/a/24503).

``````
IUS also maintains the [yum replace plugin][9] to simplify this process.

[asciinema demo][10]

```bash
yum replace php --replace-with php56u
```
``````

While rewriting this guide I felt that was sufficient.  Do you think we still need to explicitly give the yum command for installing the plugin in the usage guide?  It isn't required for using the IUS repo; as demonstrated in the documentation, it is just one of several options.  I think it might be more appropriate to include the installation command in the plugin's [README](https://github.com/iuscommunity/yum-plugin-replace/blob/master/README) instead of here.  Thoughts?

**Comment by i-give-up** [comment]
> It also includes a text example of usage and a link to an asciinema screencast demo.

Ah, I wasn't aware that the screencast demo has all those things. I guess I was only looking at the text portions.

In any case, the old guide has some explanations that would be helpful in the new guide, maybe on a separate page since like you said, it is optional for using this repo.

---

Regarding the replace plugin, the guide and the plugin's documentation don't make it clear that the plugin is available via the `yum-plugin-replace` package in the IUS repo. I think it'd be nice to have this clarified in both the IUS guide and the plugin's README. It's just one line anyway.

**Comment by carlwgeorge** [comment]
Take a look at that wording, if it needs further work send us a pull request with how you think it should look.  Thanks!
