### ISSUE TITLE
missing key

### ISSUE THREAD

**Issue by rotech1** [iuscommunity/ius.io#39]
yum-plugin-replace.noarch                  0.2.7-1.ius.el6               ius

when I update, it gives me this message:

**warning**: rpmts_HdrFromFdno: Header V4 RSA/SHA256 Signature, key ID 74271a83: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-6
Importing GPG key 0x74271A83:
 Userid : IUS (6) <dev@ius.io>
 Package: ius-release-2-1.el6.ius.noarch (@ius)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-6

not sure what to make of that...

**Comment by carlwgeorge** [comment]
IUS has switched from a mirror network to a CDN, and along with that change is using new package signing keys.  This change was discussed [here](https://github.com/iusrepo/infrastructure/issues/14) and announced [here](https://github.com/iusrepo/announce/issues/13).  I recommend you watch the [announce git repo](https://github.com/iusrepo/announce) to be aware of important changes like this.

Since yum is finding the new key on disk (`/etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-6`), it looks like you updated ius-release correctly and just need to accept the new key.
